// Code generated by goctl. DO NOT EDIT!
// Source: auth.proto

package authservice

import (
	"context"

	"github.com/showurl/Zero-IM-Server/app/auth/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	VerifyTokenReq  = pb.VerifyTokenReq
	VerifyTokenResp = pb.VerifyTokenResp

	AuthService interface {
		VerifyToken(ctx context.Context, in *VerifyTokenReq, opts ...grpc.CallOption) (*VerifyTokenResp, error)
	}

	defaultAuthService struct {
		cli zrpc.Client
	}
)

func NewAuthService(cli zrpc.Client) AuthService {
	return &defaultAuthService{
		cli: cli,
	}
}

func (m *defaultAuthService) VerifyToken(ctx context.Context, in *VerifyTokenReq, opts ...grpc.CallOption) (*VerifyTokenResp, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.VerifyToken(ctx, in, opts...)
}
