// Code generated by goctl. DO NOT EDIT!
// Source: ws.proto

package example

import (
	"github.com/showurl/Zero-IM-Server/app/msg/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
)

type (
	BlackAddedTips                = pb.BlackAddedTips
	BlackDeletedTips              = pb.BlackDeletedTips
	BlackInfo                     = pb.BlackInfo
	ConversationSetPrivateTips    = pb.ConversationSetPrivateTips
	ConversationUpdateTips        = pb.ConversationUpdateTips
	DelMsgListReq                 = pb.DelMsgListReq
	DelMsgListResp                = pb.DelMsgListResp
	Department                    = pb.Department
	DepartmentMember              = pb.DepartmentMember
	FriendAddedTips               = pb.FriendAddedTips
	FriendApplication             = pb.FriendApplication
	FriendApplicationApprovedTips = pb.FriendApplicationApprovedTips
	FriendApplicationRejectedTips = pb.FriendApplicationRejectedTips
	FriendApplicationTips         = pb.FriendApplicationTips
	FriendDeletedTips             = pb.FriendDeletedTips
	FriendInfo                    = pb.FriendInfo
	FriendInfoChangedTips         = pb.FriendInfoChangedTips
	FriendRequest                 = pb.FriendRequest
	FromToUserID                  = pb.FromToUserID
	GroupApplicationAcceptedTips  = pb.GroupApplicationAcceptedTips
	GroupApplicationRejectedTips  = pb.GroupApplicationRejectedTips
	GroupCancelMutedTips          = pb.GroupCancelMutedTips
	GroupCreatedTips              = pb.GroupCreatedTips
	GroupDismissedTips            = pb.GroupDismissedTips
	GroupInfo                     = pb.GroupInfo
	GroupInfoSetTips              = pb.GroupInfoSetTips
	GroupMemberCancelMutedTips    = pb.GroupMemberCancelMutedTips
	GroupMemberFullInfo           = pb.GroupMemberFullInfo
	GroupMemberInfoSetTips        = pb.GroupMemberInfoSetTips
	GroupMemberMutedTips          = pb.GroupMemberMutedTips
	GroupMutedTips                = pb.GroupMutedTips
	GroupOwnerTransferredTips     = pb.GroupOwnerTransferredTips
	GroupRequest                  = pb.GroupRequest
	InvitationInfo                = pb.InvitationInfo
	JoinGroupApplicationTips      = pb.JoinGroupApplicationTips
	MemberEnterTips               = pb.MemberEnterTips
	MemberInvitedTips             = pb.MemberInvitedTips
	MemberKickedTips              = pb.MemberKickedTips
	MemberQuitTips                = pb.MemberQuitTips
	MsgData                       = pb.MsgData
	OfflinePushInfo               = pb.OfflinePushInfo
	OrganizationChangedTips       = pb.OrganizationChangedTips
	OrganizationUser              = pb.OrganizationUser
	ParticipantMetaData           = pb.ParticipantMetaData
	PublicUserInfo                = pb.PublicUserInfo
	PullMessageBySeqListReq       = pb.PullMessageBySeqListReq
	PullMessageBySeqListResp      = pb.PullMessageBySeqListResp
	RequestPagination             = pb.RequestPagination
	ResponsePagination            = pb.ResponsePagination
	SignalAcceptReply             = pb.SignalAcceptReply
	SignalAcceptReq               = pb.SignalAcceptReq
	SignalCancelReply             = pb.SignalCancelReply
	SignalCancelReq               = pb.SignalCancelReq
	SignalHungUpReply             = pb.SignalHungUpReply
	SignalHungUpReq               = pb.SignalHungUpReq
	SignalInviteInGroupReply      = pb.SignalInviteInGroupReply
	SignalInviteInGroupReq        = pb.SignalInviteInGroupReq
	SignalInviteReply             = pb.SignalInviteReply
	SignalInviteReq               = pb.SignalInviteReq
	SignalRejectReply             = pb.SignalRejectReply
	SignalRejectReq               = pb.SignalRejectReq
	SignalReq                     = pb.SignalReq
	SignalResp                    = pb.SignalResp
	TipsComm                      = pb.TipsComm
	UserDepartmentMember          = pb.UserDepartmentMember
	UserInDepartment              = pb.UserInDepartment
	UserInfo                      = pb.UserInfo
	UserInfoUpdatedTips           = pb.UserInfoUpdatedTips
	UserSendMsgResp               = pb.UserSendMsgResp

	Example interface {
	}

	defaultExample struct {
		cli zrpc.Client
	}
)

func NewExample(cli zrpc.Client) Example {
	return &defaultExample{
		cli: cli,
	}
}
