// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: msgpush.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MsgPushServiceClient is the client API for MsgPushService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgPushServiceClient interface {
	PushMsg(ctx context.Context, in *PushMsgReq, opts ...grpc.CallOption) (*PushMsgResp, error)
}

type msgPushServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgPushServiceClient(cc grpc.ClientConnInterface) MsgPushServiceClient {
	return &msgPushServiceClient{cc}
}

func (c *msgPushServiceClient) PushMsg(ctx context.Context, in *PushMsgReq, opts ...grpc.CallOption) (*PushMsgResp, error) {
	out := new(PushMsgResp)
	err := c.cc.Invoke(ctx, "/pb.msgPushService/PushMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgPushServiceServer is the server API for MsgPushService service.
// All implementations must embed UnimplementedMsgPushServiceServer
// for forward compatibility
type MsgPushServiceServer interface {
	PushMsg(context.Context, *PushMsgReq) (*PushMsgResp, error)
	mustEmbedUnimplementedMsgPushServiceServer()
}

// UnimplementedMsgPushServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMsgPushServiceServer struct {
}

func (UnimplementedMsgPushServiceServer) PushMsg(context.Context, *PushMsgReq) (*PushMsgResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushMsg not implemented")
}
func (UnimplementedMsgPushServiceServer) mustEmbedUnimplementedMsgPushServiceServer() {}

// UnsafeMsgPushServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgPushServiceServer will
// result in compilation errors.
type UnsafeMsgPushServiceServer interface {
	mustEmbedUnimplementedMsgPushServiceServer()
}

func RegisterMsgPushServiceServer(s grpc.ServiceRegistrar, srv MsgPushServiceServer) {
	s.RegisterService(&MsgPushService_ServiceDesc, srv)
}

func _MsgPushService_PushMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgPushServiceServer).PushMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.msgPushService/PushMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgPushServiceServer).PushMsg(ctx, req.(*PushMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MsgPushService_ServiceDesc is the grpc.ServiceDesc for MsgPushService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MsgPushService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.msgPushService",
	HandlerType: (*MsgPushServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushMsg",
			Handler:    _MsgPushService_PushMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msgpush.proto",
}
