// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Token      string `form:"token"`
	SendID     string `form:"sendID"`
	PlatformID string `form:"platformID"`
}
type Response struct {
	Uid     string
	ErrMsg  string
	Success bool
}
