// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/showurl/Zero-IM-Server/app/msg-gateway/cmd/wsrpc/internal/wssvc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *wssvc.ServiceContext) {
	//http.HandleFunc("/", MsggatewayHandler(serverCtx))
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: MsggatewayHandler(serverCtx),
			},
		},
	)
}
