// Code generated by goctl. DO NOT EDIT!
// Source: auth.proto

package server

import (
	"context"

	"github.com/showurl/Zero-IM-Server/app/auth/cmd/rpc/internal/logic"
	"github.com/showurl/Zero-IM-Server/app/auth/cmd/rpc/internal/svc"
	"github.com/showurl/Zero-IM-Server/app/auth/cmd/rpc/pb"
)

type AuthServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAuthServiceServer
}

func NewAuthServiceServer(svcCtx *svc.ServiceContext) *AuthServiceServer {
	return &AuthServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthServiceServer) VerifyToken(ctx context.Context, in *pb.VerifyTokenReq) (*pb.VerifyTokenResp, error) {
	l := logic.NewVerifyTokenLogic(ctx, s.svcCtx)
	return l.VerifyToken(in)
}
