// Code generated by goctl. DO NOT EDIT!
// Source: msgpush.proto

package msgpushservice

import (
	"context"

	"github.com/showurl/Zero-IM-Server/app/msg-push/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PushMsgReq  = pb.PushMsgReq
	PushMsgResp = pb.PushMsgResp

	MsgPushService interface {
		PushMsg(ctx context.Context, in *PushMsgReq, opts ...grpc.CallOption) (*PushMsgResp, error)
	}

	defaultMsgPushService struct {
		cli zrpc.Client
	}
)

func NewMsgPushService(cli zrpc.Client) MsgPushService {
	return &defaultMsgPushService{
		cli: cli,
	}
}

func (m *defaultMsgPushService) PushMsg(ctx context.Context, in *PushMsgReq, opts ...grpc.CallOption) (*PushMsgResp, error) {
	client := pb.NewMsgPushServiceClient(m.cli.Conn())
	return client.PushMsg(ctx, in, opts...)
}
