// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: im-user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecvMsgOpt int32

const (
	RecvMsgOpt_ReceiveMessage          RecvMsgOpt = 0
	RecvMsgOpt_NotReceiveMessage       RecvMsgOpt = 1
	RecvMsgOpt_ReceiveNotNotifyMessage RecvMsgOpt = 2
)

// Enum value maps for RecvMsgOpt.
var (
	RecvMsgOpt_name = map[int32]string{
		0: "ReceiveMessage",
		1: "NotReceiveMessage",
		2: "ReceiveNotNotifyMessage",
	}
	RecvMsgOpt_value = map[string]int32{
		"ReceiveMessage":          0,
		"NotReceiveMessage":       1,
		"ReceiveNotNotifyMessage": 2,
	}
)

func (x RecvMsgOpt) Enum() *RecvMsgOpt {
	p := new(RecvMsgOpt)
	*p = x
	return p
}

func (x RecvMsgOpt) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecvMsgOpt) Descriptor() protoreflect.EnumDescriptor {
	return file_im_user_proto_enumTypes[0].Descriptor()
}

func (RecvMsgOpt) Type() protoreflect.EnumType {
	return &file_im_user_proto_enumTypes[0]
}

func (x RecvMsgOpt) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecvMsgOpt.Descriptor instead.
func (RecvMsgOpt) EnumDescriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{0}
}

type CommonResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode int32  `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{0}
}

func (x *CommonResp) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *CommonResp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID         string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Nickname       string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	FaceURL        string `protobuf:"bytes,3,opt,name=faceURL,proto3" json:"faceURL,omitempty"`
	Gender         int32  `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`
	PhoneNumber    string `protobuf:"bytes,5,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Birth          uint32 `protobuf:"varint,6,opt,name=birth,proto3" json:"birth,omitempty"`
	Email          string `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Ex             string `protobuf:"bytes,8,opt,name=ex,proto3" json:"ex,omitempty"`
	CreateTime     uint32 `protobuf:"varint,9,opt,name=createTime,proto3" json:"createTime,omitempty"`
	AppMangerLevel int32  `protobuf:"varint,10,opt,name=appMangerLevel,proto3" json:"appMangerLevel,omitempty"`
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetFaceURL() string {
	if x != nil {
		return x.FaceURL
	}
	return ""
}

func (x *UserInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserInfo) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserInfo) GetBirth() uint32 {
	if x != nil {
		return x.Birth
	}
	return 0
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

func (x *UserInfo) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *UserInfo) GetAppMangerLevel() int32 {
	if x != nil {
		return x.AppMangerLevel
	}
	return 0
}

type GetGroupMemberIDListFromCacheReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupID string `protobuf:"bytes,1,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
}

func (x *GetGroupMemberIDListFromCacheReq) Reset() {
	*x = GetGroupMemberIDListFromCacheReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupMemberIDListFromCacheReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMemberIDListFromCacheReq) ProtoMessage() {}

func (x *GetGroupMemberIDListFromCacheReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMemberIDListFromCacheReq.ProtoReflect.Descriptor instead.
func (*GetGroupMemberIDListFromCacheReq) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetGroupMemberIDListFromCacheReq) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

type GetGroupMemberIDListFromCacheResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonResp   *CommonResp `protobuf:"bytes,1,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	MemberIDList []string    `protobuf:"bytes,2,rep,name=memberIDList,proto3" json:"memberIDList,omitempty"`
}

func (x *GetGroupMemberIDListFromCacheResp) Reset() {
	*x = GetGroupMemberIDListFromCacheResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupMemberIDListFromCacheResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMemberIDListFromCacheResp) ProtoMessage() {}

func (x *GetGroupMemberIDListFromCacheResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMemberIDListFromCacheResp.ProtoReflect.Descriptor instead.
func (*GetGroupMemberIDListFromCacheResp) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetGroupMemberIDListFromCacheResp) GetCommonResp() *CommonResp {
	if x != nil {
		return x.CommonResp
	}
	return nil
}

func (x *GetGroupMemberIDListFromCacheResp) GetMemberIDList() []string {
	if x != nil {
		return x.MemberIDList
	}
	return nil
}

type IfAInBBlacklistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AUserID string `protobuf:"bytes,1,opt,name=aUserID,proto3" json:"aUserID,omitempty"`
	BUserID string `protobuf:"bytes,2,opt,name=bUserID,proto3" json:"bUserID,omitempty"`
}

func (x *IfAInBBlacklistReq) Reset() {
	*x = IfAInBBlacklistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IfAInBBlacklistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfAInBBlacklistReq) ProtoMessage() {}

func (x *IfAInBBlacklistReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfAInBBlacklistReq.ProtoReflect.Descriptor instead.
func (*IfAInBBlacklistReq) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{4}
}

func (x *IfAInBBlacklistReq) GetAUserID() string {
	if x != nil {
		return x.AUserID
	}
	return ""
}

func (x *IfAInBBlacklistReq) GetBUserID() string {
	if x != nil {
		return x.BUserID
	}
	return ""
}

type IfAInBBlacklistResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonResp    *CommonResp `protobuf:"bytes,1,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	IsInBlacklist bool        `protobuf:"varint,2,opt,name=isInBlacklist,proto3" json:"isInBlacklist,omitempty"`
}

func (x *IfAInBBlacklistResp) Reset() {
	*x = IfAInBBlacklistResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IfAInBBlacklistResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfAInBBlacklistResp) ProtoMessage() {}

func (x *IfAInBBlacklistResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfAInBBlacklistResp.ProtoReflect.Descriptor instead.
func (*IfAInBBlacklistResp) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{5}
}

func (x *IfAInBBlacklistResp) GetCommonResp() *CommonResp {
	if x != nil {
		return x.CommonResp
	}
	return nil
}

func (x *IfAInBBlacklistResp) GetIsInBlacklist() bool {
	if x != nil {
		return x.IsInBlacklist
	}
	return false
}

type IfAInBFriendListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AUserID string `protobuf:"bytes,1,opt,name=aUserID,proto3" json:"aUserID,omitempty"`
	BUserID string `protobuf:"bytes,2,opt,name=bUserID,proto3" json:"bUserID,omitempty"`
}

func (x *IfAInBFriendListReq) Reset() {
	*x = IfAInBFriendListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IfAInBFriendListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfAInBFriendListReq) ProtoMessage() {}

func (x *IfAInBFriendListReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfAInBFriendListReq.ProtoReflect.Descriptor instead.
func (*IfAInBFriendListReq) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{6}
}

func (x *IfAInBFriendListReq) GetAUserID() string {
	if x != nil {
		return x.AUserID
	}
	return ""
}

func (x *IfAInBFriendListReq) GetBUserID() string {
	if x != nil {
		return x.BUserID
	}
	return ""
}

type IfAInBFriendListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonResp     *CommonResp `protobuf:"bytes,1,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	IsInFriendList bool        `protobuf:"varint,2,opt,name=isInFriendList,proto3" json:"isInFriendList,omitempty"`
}

func (x *IfAInBFriendListResp) Reset() {
	*x = IfAInBFriendListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IfAInBFriendListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfAInBFriendListResp) ProtoMessage() {}

func (x *IfAInBFriendListResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfAInBFriendListResp.ProtoReflect.Descriptor instead.
func (*IfAInBFriendListResp) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{7}
}

func (x *IfAInBFriendListResp) GetCommonResp() *CommonResp {
	if x != nil {
		return x.CommonResp
	}
	return nil
}

func (x *IfAInBFriendListResp) GetIsInFriendList() bool {
	if x != nil {
		return x.IsInFriendList
	}
	return false
}

type GetSingleConversationRecvMsgOptsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID         string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ConversationID string `protobuf:"bytes,2,opt,name=conversationID,proto3" json:"conversationID,omitempty"`
}

func (x *GetSingleConversationRecvMsgOptsReq) Reset() {
	*x = GetSingleConversationRecvMsgOptsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSingleConversationRecvMsgOptsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleConversationRecvMsgOptsReq) ProtoMessage() {}

func (x *GetSingleConversationRecvMsgOptsReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleConversationRecvMsgOptsReq.ProtoReflect.Descriptor instead.
func (*GetSingleConversationRecvMsgOptsReq) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetSingleConversationRecvMsgOptsReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *GetSingleConversationRecvMsgOptsReq) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

type GetSingleConversationRecvMsgOptsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonResp *CommonResp `protobuf:"bytes,1,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	Opts       RecvMsgOpt  `protobuf:"varint,2,opt,name=opts,proto3,enum=imuser.RecvMsgOpt" json:"opts,omitempty"`
}

func (x *GetSingleConversationRecvMsgOptsResp) Reset() {
	*x = GetSingleConversationRecvMsgOptsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSingleConversationRecvMsgOptsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleConversationRecvMsgOptsResp) ProtoMessage() {}

func (x *GetSingleConversationRecvMsgOptsResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleConversationRecvMsgOptsResp.ProtoReflect.Descriptor instead.
func (*GetSingleConversationRecvMsgOptsResp) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetSingleConversationRecvMsgOptsResp) GetCommonResp() *CommonResp {
	if x != nil {
		return x.CommonResp
	}
	return nil
}

func (x *GetSingleConversationRecvMsgOptsResp) GetOpts() RecvMsgOpt {
	if x != nil {
		return x.Opts
	}
	return RecvMsgOpt_ReceiveMessage
}

var File_im_user_proto protoreflect.FileDescriptor

var file_im_user_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x69, 0x6d, 0x2d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x69, 0x6d, 0x75, 0x73, 0x65, 0x72, 0x22, 0x3e, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x96, 0x02, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08,
	0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x61, 0x63, 0x65,
	0x55, 0x52, 0x4c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x61, 0x63, 0x65, 0x55,
	0x52, 0x4c, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x62, 0x69, 0x72, 0x74, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x62, 0x69, 0x72,
	0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x65, 0x78, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x65, 0x78, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x61, 0x70, 0x70, 0x4d,
	0x61, 0x6e, 0x67, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0e, 0x61, 0x70, 0x70, 0x4d, 0x61, 0x6e, 0x67, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x22, 0x3c, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x22, 0x7b,
	0x0a, 0x21, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x0a, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x48, 0x0a, 0x12, 0x49,
	0x66, 0x41, 0x49, 0x6e, 0x42, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x62,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x6f, 0x0a, 0x13, 0x49, 0x66, 0x41, 0x49, 0x6e, 0x42, 0x42,
	0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x0a,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x24, 0x0a, 0x0d, 0x69, 0x73, 0x49, 0x6e, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x69, 0x73, 0x49, 0x6e, 0x42, 0x6c, 0x61,
	0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x49, 0x0a, 0x13, 0x49, 0x66, 0x41, 0x49, 0x6e, 0x42,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x22, 0x72, 0x0a, 0x14, 0x49, 0x66, 0x41, 0x49, 0x6e, 0x42, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x0a, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x69, 0x6d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a,
	0x0e, 0x69, 0x73, 0x49, 0x6e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x69, 0x73, 0x49, 0x6e, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x65, 0x0a, 0x23, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67,
	0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x63, 0x76, 0x4d, 0x73, 0x67, 0x4f, 0x70, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f,
	0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x22, 0x82, 0x01, 0x0a,
	0x24, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72,
	0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x76, 0x4d, 0x73, 0x67, 0x4f, 0x70, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x69, 0x6d, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x0a, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x04, 0x6f, 0x70, 0x74,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x52, 0x65, 0x63, 0x76, 0x4d, 0x73, 0x67, 0x4f, 0x70, 0x74, 0x52, 0x04, 0x6f, 0x70, 0x74,
	0x73, 0x2a, 0x54, 0x0a, 0x0a, 0x52, 0x65, 0x63, 0x76, 0x4d, 0x73, 0x67, 0x4f, 0x70, 0x74, 0x12,
	0x12, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x4e, 0x6f, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x10, 0x01, 0x12, 0x1b, 0x0a, 0x17, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x4e, 0x6f, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x10, 0x02, 0x32, 0x9f, 0x03, 0x0a, 0x0d, 0x69, 0x6d, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x74, 0x0a, 0x1d, 0x47, 0x65, 0x74,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x44, 0x4c, 0x69, 0x73,
	0x74, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x28, 0x2e, 0x69, 0x6d, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x29, 0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65,
	0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x44, 0x4c, 0x69,
	0x73, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x4a, 0x0a, 0x0f, 0x49, 0x66, 0x41, 0x49, 0x6e, 0x42, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69,
	0x73, 0x74, 0x12, 0x1a, 0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x49, 0x66, 0x41, 0x49,
	0x6e, 0x42, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1b,
	0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x49, 0x66, 0x41, 0x49, 0x6e, 0x42, 0x42, 0x6c,
	0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4d, 0x0a, 0x10, 0x49,
	0x66, 0x41, 0x49, 0x6e, 0x42, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x1b, 0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x49, 0x66, 0x41, 0x49, 0x6e, 0x42, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x69,
	0x6d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x49, 0x66, 0x41, 0x49, 0x6e, 0x42, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x7d, 0x0a, 0x20, 0x47, 0x65,
	0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x76, 0x4d, 0x73, 0x67, 0x4f, 0x70, 0x74, 0x73, 0x12, 0x2b,
	0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63,
	0x76, 0x4d, 0x73, 0x67, 0x4f, 0x70, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x2c, 0x2e, 0x69, 0x6d,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x43, 0x6f,
	0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x76, 0x4d, 0x73,
	0x67, 0x4f, 0x70, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_im_user_proto_rawDescOnce sync.Once
	file_im_user_proto_rawDescData = file_im_user_proto_rawDesc
)

func file_im_user_proto_rawDescGZIP() []byte {
	file_im_user_proto_rawDescOnce.Do(func() {
		file_im_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_im_user_proto_rawDescData)
	})
	return file_im_user_proto_rawDescData
}

var file_im_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_im_user_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_im_user_proto_goTypes = []interface{}{
	(RecvMsgOpt)(0),                              // 0: imuser.RecvMsgOpt
	(*CommonResp)(nil),                           // 1: imuser.CommonResp
	(*UserInfo)(nil),                             // 2: imuser.UserInfo
	(*GetGroupMemberIDListFromCacheReq)(nil),     // 3: imuser.GetGroupMemberIDListFromCacheReq
	(*GetGroupMemberIDListFromCacheResp)(nil),    // 4: imuser.GetGroupMemberIDListFromCacheResp
	(*IfAInBBlacklistReq)(nil),                   // 5: imuser.IfAInBBlacklistReq
	(*IfAInBBlacklistResp)(nil),                  // 6: imuser.IfAInBBlacklistResp
	(*IfAInBFriendListReq)(nil),                  // 7: imuser.IfAInBFriendListReq
	(*IfAInBFriendListResp)(nil),                 // 8: imuser.IfAInBFriendListResp
	(*GetSingleConversationRecvMsgOptsReq)(nil),  // 9: imuser.GetSingleConversationRecvMsgOptsReq
	(*GetSingleConversationRecvMsgOptsResp)(nil), // 10: imuser.GetSingleConversationRecvMsgOptsResp
}
var file_im_user_proto_depIdxs = []int32{
	1,  // 0: imuser.GetGroupMemberIDListFromCacheResp.commonResp:type_name -> imuser.CommonResp
	1,  // 1: imuser.IfAInBBlacklistResp.commonResp:type_name -> imuser.CommonResp
	1,  // 2: imuser.IfAInBFriendListResp.commonResp:type_name -> imuser.CommonResp
	1,  // 3: imuser.GetSingleConversationRecvMsgOptsResp.commonResp:type_name -> imuser.CommonResp
	0,  // 4: imuser.GetSingleConversationRecvMsgOptsResp.opts:type_name -> imuser.RecvMsgOpt
	3,  // 5: imuser.imUserService.GetGroupMemberIDListFromCache:input_type -> imuser.GetGroupMemberIDListFromCacheReq
	5,  // 6: imuser.imUserService.IfAInBBlacklist:input_type -> imuser.IfAInBBlacklistReq
	7,  // 7: imuser.imUserService.IfAInBFriendList:input_type -> imuser.IfAInBFriendListReq
	9,  // 8: imuser.imUserService.GetSingleConversationRecvMsgOpts:input_type -> imuser.GetSingleConversationRecvMsgOptsReq
	4,  // 9: imuser.imUserService.GetGroupMemberIDListFromCache:output_type -> imuser.GetGroupMemberIDListFromCacheResp
	6,  // 10: imuser.imUserService.IfAInBBlacklist:output_type -> imuser.IfAInBBlacklistResp
	8,  // 11: imuser.imUserService.IfAInBFriendList:output_type -> imuser.IfAInBFriendListResp
	10, // 12: imuser.imUserService.GetSingleConversationRecvMsgOpts:output_type -> imuser.GetSingleConversationRecvMsgOptsResp
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_im_user_proto_init() }
func file_im_user_proto_init() {
	if File_im_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_im_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupMemberIDListFromCacheReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupMemberIDListFromCacheResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IfAInBBlacklistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IfAInBBlacklistResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IfAInBFriendListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IfAInBFriendListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSingleConversationRecvMsgOptsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSingleConversationRecvMsgOptsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_im_user_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_im_user_proto_goTypes,
		DependencyIndexes: file_im_user_proto_depIdxs,
		EnumInfos:         file_im_user_proto_enumTypes,
		MessageInfos:      file_im_user_proto_msgTypes,
	}.Build()
	File_im_user_proto = out.File
	file_im_user_proto_rawDesc = nil
	file_im_user_proto_goTypes = nil
	file_im_user_proto_depIdxs = nil
}
