global:
  scrape_interval:
  external_labels:
    monitor: 'zero-im-server-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s  #global catch time
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'msggateway-rpc'
    static_configs:
      - targets: ['192.168.2.77:10401']
        labels:
          job: msggateway-rpc
          app: msggateway-rpc
          env: dev

  - job_name: 'auth-rpc'
    static_configs:
      - targets: ['192.168.2.77:10161']
        labels:
          job: msggateway-rpc
          app: msggateway-rpc
          env: dev

  - job_name: 'imuser-rpc'
    static_configs:
      - targets: ['192.168.2.77:10241']
        labels:
          job: msggateway-rpc
          app: msggateway-rpc
          env: dev

  - job_name: 'msg-rpc'
    static_configs:
      - targets: ['192.168.2.77:10131']
        labels:
          job: msggateway-rpc
          app: msggateway-rpc
          env: dev
