// Code generated by goctl. DO NOT EDIT!
// Source: ws.proto

package server

import (
	"github.com/showurl/Zero-IM-Server/app/msg/cmd/rpc/internal/svc"
	"github.com/showurl/Zero-IM-Server/app/msg/cmd/rpc/pb"
)

type ExampleServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedExampleServer
}

func NewExampleServer(svcCtx *svc.ServiceContext) *ExampleServer {
	return &ExampleServer{
		svcCtx: svcCtx,
	}
}
